export default {
  phonenumber: 'Số điện thoại',
  password: 'Mật khẩu',
  login: 'Đăng nhập',
  register: 'Đăng ký',
  createNewAcc: 'Tạo tài khoản Facebook mới',
  or: 'HOẶC',
  forgotPassword: 'Quên mật khẩu?',
  hadAccount: 'Bạn đã có tài khoản?',
  start: 'Bắt đầu',
  startTitle: 'Tham gia Facebook',
  startLabel: 'Chúng tôi sẽ giúp bạn tạo tài khoản sau vài bước dễ dàng.',
  yourName: 'Bạn tên gì?',
  yourNameLabel: 'Dùng tên thật giúp bạn bè dễ dàng nhận ra bạn hơn.',
  continue: 'Tiếp',
  return: 'Quay lại',
  firstName: 'Họ',
  lastName: 'Tên',
  birthdayTitle: 'Khi nào là Sinh nhật của bạn?',
  genderTitle: 'Giới tính của bạn là gì?',
  male: 'Nam',
  female: 'Nữ',
  other: 'Khác',
  loginInfoTitle: 'Thông tin đăng nhập',
  nameError: 'Họ và tên không được để trống.',
  birthdayError: 'Ngày sinh không hợp lệ.',
  phonenumberError: 'Số điện thoại không được để trống.',
  passwordError: 'Mật khẩu phải có tối thiểu 8 ký tự.',
  loginError: 'Số điện thoại và mật khẩu không được để trống.',
  birthdayFormat: '[ngày] DD [tháng] MM, YYYY',
  phonenumberNotValid: 'Số điện thoại không hợp lệ.',
  passwordNotValid: 'Mật khẩu chứa ký tự không hợp lệ.',
};
