export default {
  createPost: 'Tạo bài viết',
  post: 'ĐĂNG',
  public: 'Công khai',
  postPlaceholder: 'Bạn đang nghĩ gì?',
  image: 'Ảnh',
  video: 'Video',
  emo: 'Cảm xúc/Hoạt động',
  like: 'Thích',
  comment: 'Bình luận',
  comments: ' bình luận',
  postOf: 'Bài viết của ',
  editPost: 'Chỉnh sửa bài viết',
  deletePost: 'Chuyển vào thùng rác',
  save: 'LƯU',
};
