export default {
  createPost: 'Tạo bài viết',
  post: 'ĐĂNG',
  public: 'Công khai',
  postPlaceholder: 'Bạn đang nghĩ gì?',
  image: 'Ảnh',
  video: 'Video',
  emo: 'Cảm xúc/Hoạt động',
  like: 'Thích',
  comment: 'Bình luận',
  comments: ' bình luận',
  postOf: 'Bài viết của ',
  editPost: 'Chỉnh sửa bài viết',
  deletePost: 'Chuyển vào thùng rác',
  save: 'LƯU',
  saveDraftTitle: 'Lưu bài viết này dưới dạng bản nháp?',
  saveDraftContent: 'Nếu bỏ bây giờ, bạn sẽ mất bài viết này.',
  saveDraftConfirm: 'Lưu bản nháp',
  saveDraftCancel: 'Bỏ bài viết',
  continueEdit: 'Tiếp tục chỉnh sửa',
  confirmDeleteTitle: 'Chuyển vào thùng rác?',
  confirmDeleteContent:
    'Bài viết sẽ được chuyển đến thùng rác. Bạn có thể xoác các mục này sớm hơn khỏi Thùng rác bằng cách đi đến Nhật ký hoạt động trong phần Cài đặt.',
  confirmDeleteConfirm: 'Chuyển',
  confirmDeleteCancel: 'Hủy',
  confirmCancelEditTitle: 'Bỏ thay đổi?',
  confirmCancelEditContent: 'Nếu bạn hủy bây giờ, thay đổi của bạn sẽ bị bỏ.',
  confirmCancelEditCancel: 'Bỏ',
  reply: 'Phản hồi',
  reply1: ' phản hồi',
  seeMore: 'Xem thêm bình luận',
  writeComment: 'Viết bình luận...',
  done: 'Xong',
};
